routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Route::resource('jobs', 'JobsController')->middleware('auth');

Auth::routes();

Route::get('jobs/delete/{id}','JobsController@destroy')->name('job.delete');

Route::get('/openOrders','JobsController@openOrders')->name('jobs.openOrders')->middleware('auth');

Route::resource('users', 'UsersController')->middleware('auth');

Route::resource('customers', 'CustomersController')->middleware('auth');

Route::get('users/delete/{id}','UsersController@destroy')->name('user.delete');

Route::get('customers/delete/{id}','CustomersController@destroy')->name('customers.delete');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('jobs/changestatus/{jid}/{sid}','JobsController@changeStatus')->name('job.changestatus');

Route::get('jobs/changeuser/{jid}/{uid?}','JobsController@changeUser')->name('job.changeuser');

Route::get('/verify','Auth\RegisterController@verifyUser')->name('verify.user');

Route::get('jobs/download/{id}', 'JobsController@download')->name('job.pdf');

Route::get('service', 'PagesController@getContact')->name('pages.service');

Route::post('service', 'PagesController@postContact');

Route::get('users/userprofile/{id}', 'UsersController@userProfile')->name('users.profile')->middleware('auth');

resources/views/home.blade.php
@extends('layouts.newhome')
@section('title', 'home page')

@section('content')
    <!-- Page Content -->
    <div class="container">

        <h1 class="my-4" style="color:red">{{ Auth::user()->name }} Welcome to Your Business</h1>

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="card h-80">
                    <h4 class="card-header">Orders</h4>
                    <div class="card-body">
                        <p class="card-text">You can manage your order</p>
                        <p>Number of orders : {{ $jobs->count() }}</p>
                        <p>Total revenue : {{ number_format($jobs->sum('price')) }} ₪</p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('jobs.index') }}" class="btn btn-primary">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-80">
                    <h4 class="card-header">Open Orders</h4>
                    <div class="card-body">
                        <p class="card-text">You can see and manage your open order</p>
                        <p>Number of open orders : {{ $openJobs->count() }}</p>
                        <p>Total revenue : {{ number_format($openJobs->sum('price')) }} ₪</p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('jobs.openOrders') }}" class="btn btn-primary">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                    <h4 class="card-header">My Orders</h4>
                    <div class="card-body">
                        <p class="card-text">You can manage orders that open by your user</p>
                        <p>Number of open orders : {{ $myjobs->count() }}</p>
                        <p>Total revenue : {{ number_format($myjobs->sum('price')) }} ₪</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-4">
                <div class="card h-90">
                    <h4 class="card-header">Customers</h4>
                    <div class="card-body">
                        <p class="card-text">You can see all your special customers</p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('customers.index') }}" class="btn btn-primary">Learn More</a>
                    </div>
                </div>
            </div>
            @if (!Auth::guest())
                @if (Auth::user()->isAdmin())
                    <div class="col-lg-4 mb-4">
                        <div class="card h-80">
                            <h4 class="card-header">Users</h4>
                            <div class="card-body">
                                <p class="card-text">As Admin you can manage your users</p>
                            </div>
                            <div class="card-footer">
                                <a href="{{ route('users.index') }}" class="btn btn-primary">Learn More</a>
                            </div>
                        </div>

                    </div>
                @endif
            @endif
            <div class="w-50 p-3" style=" position: absolute; left:63.5%; top:63%;">
                <img class=" w-50  rounded float-left" src="{{ url('/images/newlogo.jpeg') }}" alt="Responsive image">
            </div>
        </div>


    </div>
    <!-- /.row -->
@endsection